version: '3'
services:
    servera:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./servera
        ports:
            - '8081:8080'
    serverb:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./serverb
        ports:
            - '8082:8080'
    serverc:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./serverc
        ports:
            - '8083:8080'
    webhost:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./Webproxy
        ports:
            - "8080:80"
    